services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - go_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_HOST: ${DB_HOST}
      HTTP_PORT: ${HTTP_PORT}
    ports:
      - "8080:8080"
  go_db:
    container_name: go_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "${DB_PORT}:${DB_PORT}"